### ISSUE TITLE
Secss.php文件问题请教

### ISSUE THREAD

**Issue by ZooYuu** [ddvphp/chinapay#1]
请问这个文件是通过银联官网提供的NetPayClient for PHP的脚本，解密出来的源码么？我尝试过解密脚本，最后得到一堆乱码，请教一下，git主是如何操作的？

**Comment by yuchonghua** [comment]
是的，这个自己去看他代码的实现原理，就可以进行操作，看到每个变量代表的意思

**Comment by ZooYuu** [comment]
搞出来了，蛋疼…… 差点以为是递归eval 谢谢啦
